### ISSUE TITLE
How to toggle light dark modes?

### ISSUE THREAD

**Issue by wviana** [Xe/Xess#2]
Hello,

I've changed just to `@media (prefers-color-scheme: dark) {`.
What would be the "right way" to toggle to light mode?
Want my site to be default dark, but as light is already implemented, would like to give the option.

**Comment by wviana** [comment]
Never mind,
Just extracted the colors into variables, than I toggle class `.light` to root element.
```css
:root {
  --background:     #282828;
  --color:          #ebdbb2;
  --pre-background: #3c3836;
  --a-background:   #1d2021;
  --a-color:        #b16286;
  --quote-border:   #bdae93;
}

:root.light {
  --background:     #fbf1c7;
  --color:          #3c3836;
  --pre-background: #ebdbb2;
  --a-background:   #f9f5d7;
  --a-color:        #b16286;
  --quote-border:   #655c54;
}
```

**Comment by Xe** [comment]
You toggle it using OS settings. This is kinda intentional so that there is no JavaScript requirement.

**Comment by wviana** [comment]
At this point I'm using these configs for dark and light theme.
```css
:root {
  /** gruvbox palette ( from: https://github.com/ellisonleao/gruvbox.nvim/blob/72eb93408e6e27ada50d501a1cc3e0ebded95b6f/lua/gruvbox/colors.lua ) **/
  --dark0_hard:     #1d2021;
  --dark0:          #282828;
  --dark0_soft:     #32302f;
  --dark1:          #3c3836;
  --dark2:          #504945;
  --dark3:          #665c54;
  --dark4:          #7c6f64;
  --light0_hard:    #f9f5d7;
  --light0:         #fbf1c7;
  --light0_soft:    #f2e5bc;
  --light1:         #ebdbb2;
  --light2:         #d5c4a1;
  --light3:         #bdae93;
  --light4:         #a89984;
  --bright_red:     #fb4934;
  --bright_green:   #b8bb26;
  --bright_yellow:  #fabd2f;
  --bright_blue:    #83a598;
  --bright_purple:  #d3869b;
  --bright_aqua:    #8ec07c;
  --bright_orange:  #fe8019;
  --neutral_red:    #cc241d;
  --neutral_green:  #98971a;
  --neutral_yellow: #d79921;
  --neutral_blue:   #458588;
  --neutral_purple: #b16286;
  --neutral_aqua:   #689d6a;
  --neutral_orange: #d65d0e;
  --faded_red:      #9d0006;
  --faded_green:    #79740e;
  --faded_yellow:   #b57614;
  --faded_blue:     #076678;
  --faded_purple:   #8f3f71;
  --faded_aqua:     #427b58;
  --faded_orange:   #af3a03;
  --gray:           #928374;

  /** xess configs **/
  --background:     var(--dark0);
  --color:          var(--light1);
  --pre-background: var(--dark1);
  --a-background:   var(--dark0_hard);
  --a-color:        var(--bright_yellow);
  --quote-border:   var(--light3);
}

:root[data-light] {
  --background:     var(--light0);
  --color:          var(--dark1);
  --pre-background: var(--light1);
  --a-background:   var(--light0_hard);
  --a-color:        var(--neutral_yellow);
  --quote-border:   var(--dark3);
}
```

For switch between Dark and Light I'm using the follow JS:
```js
    const toggle_dark_mode = document.querySelector('#toggle_dark_mode')
    toggle_dark_mode.addEventListener('click',
      () => document.documentElement.toggleAttribute('data-light'))
```
